name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'boards/**'
      - 'extend/**'
      - 'builder/**'
      - 'examples/**'
      - '**.json'
      - '**.py'

jobs:
  CodeCheck:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: cppcheck
      uses: Qful/check-action@master
      with:
        github_token: ${{ secrets.OSQ_REPO_TOKEN }}
        enable: all
        inconclusive: disable
        inline_suppression: disable
        force_language: c
        force: enable
        max_ctu_depth: 2
        std: c11
        output_file: ./codecheck.txt
        other_options: --bug-hunting --verbose --std=c99

    - name: report
      uses: Qful/check-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        BRANCH_NAME: 'master'

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: code_check_report
        path: codecheck.txt

  build:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "blink"
          - "uart"
          - "native-blink"
          # - "arduino-hx712"
          # - "arduino-ads1255"
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pio
        run: |
          pip install -U https://github.com/OS-Q/pio/archive/main.zip
          pio platform install file://.

      - name: Build examples
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}

      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: ${{ matrix.example }}
          path: examples/${{ matrix.example }}
